sulu_trash.trash_items:
    type: rest
    name_prefix: sulu_trash.
    resource: sulu_trash.trash_item_controller

sulu_trash.post_trash-item_trigger:
    path: /trash-items/{id}.{_format}
    methods: POST
    defaults:
        _controller: sulu_trash.trash_item_controller::postTriggerAction
        _format: json
