sulu_security.roles_navigation:
    path: /navigation/roles
    defaults: { _controller: SuluSecurityBundle:Navigation:roles }

sulu_security.template.role.form:
     path: /template/role/form.html
     defaults:
         _controller: SuluSecurityBundle:Template:roleform

sulu_security.template.permission.form:
     path: /template/permission/form.html
     defaults:
         _controller: SuluSecurityBundle:Template:permissionform

sulu_security.template.role.list:
    pattern: /template/role/list.html
    defaults: { _controller: SuluSecurityBundle:Template:roleList }
