fos_http_cache:
    proxy_client:
        symfony:
            use_kernel_dispatcher: true

# activate the following for user context based caching
# see https://foshttpcachebundle.readthedocs.io/en/latest/features/user-context.html
# for additional needed changes
#    user_context:
#        enabled: true
#        role_provider: true
