sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - downloads

env:
  global:
    - JACKRABBIT_VERSION=2.12.0
    - SYMFONY__PHPCR__TRANSPORT=doctrinedbal
    - TEST_FLAGS=""
    - SYMFONY__DATABASE__DRIVER=pdo_mysql
    - SYMFONY__DATABASE__CHARSET=utf8mb4
    - SYMFONY__DATABASE__COLLATE=utf8mb4_unicode_ci

matrix:
  include:
    - language: php
      php: 7.1
      before_script: bin/travis/before_script_php.sh
      script: ./bin/runtests -i -a $TEST_FLAGS
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

    - language: php
      php: 7.1
      before_script: bin/travis/before_script_php.sh
      script: ./bin/runtests -i -a $TEST_FLAGS
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
        - SYMFONY__DATABASE__DRIVER=pdo_pgsql
        - SYMFONY__DATABASE__USER=postgres
        - SYMFONY__DATABASE__PASSWORD=postgres
        - SYMFONY__PHPCR__TRANSPORT=jackrabbit
        - SYMFONY__DATABASE__CHARSET=UTF8
        - SYMFONY__DATABASE__COLLATE=
        # restart jackrabbit after each suite see: https://github.com/sulu-io/sulu/issues/2137
        - TEST_FLAGS="--jackrabbit-restart"

    - language: node_js
      node_js: "8"
      script: bin/travis/script_js.sh

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
