sudo: false

language: php

php: 7.1

cache:
  directories:
    - $HOME/.composer/cache
    - downloads

env:
  global:
    - JACKRABBIT_VERSION=2.12.0
    - SYMFONY__PHPCR__TRANSPORT=doctrinedbal
    - TEST_FLAGS=""
    - SYMFONY__DATABASE__DRIVER=pdo_mysql
    - PHP=false
    - JS=false

matrix:
  include:
    - env:
        - PHP=true
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
    - env:
        - PHP=true
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
        - SYMFONY__DATABASE__DRIVER=pdo_pgsql
        - SYMFONY__DATABASE__USER=postgres
        - SYMFONY__DATABASE__PASSWORD=postgres
        - SYMFONY__PHPCR__TRANSPORT=jackrabbit
        # restart jackrabbit after each suite see: https://github.com/sulu-io/sulu/issues/2137
        - TEST_FLAGS="--jackrabbit-restart"
    - node_js: "node"
      env:
        - JS=true

before_script:
  - if [[ $PHP = true ]]; then bin/travis/before_script_php.sh; fi
  - if [[ $JS = true ]]; then nvm install node; npm install -g npm; npm install; fi

script:
  - if [[ $PHP = true ]]; then time ./bin/runtests -i -a $TEST_FLAGS; fi
  - if [[ $JS = true ]]; then bin/travis/script_js.sh; fi

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
