sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - downloads

env:
  global:
    - JACKRABBIT_VERSION=2.12.0
    - SULU_PHPCR_TRANSPORT=doctrinedbal
    - TEST_FLAGS=""
    - SULU_DATABASE_DRIVER=pdo_mysql
    - SULU_DATABASE_CHARSET=utf8mb4
    - SULU_DATABASE_COLLATE=utf8mb4_unicode_ci

matrix:
  include:
    - language: php
      php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

    - language: php
      php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
        - SULU_DATABASE_DRIVER=pdo_pgsql
        - SULU_DATABASE_USER=postgres
        - SULU_DATABASE_PASSWORD=postgres
        - SULU_PHPCR_TRANSPORT=jackrabbit
        - SULU_DATABASE_CHARSET=UTF8
        - SULU_DATABASE_COLLATE=
        # restart jackrabbit after each suite see: https://github.com/sulu-io/sulu/issues/2137
        - TEST_FLAGS="--jackrabbit-restart"

# Sqlite support: https://github.com/sulu/sulu/issues/2048
#
#    - language: php
#      php: 7.1
#      env:
#        - SULU_DATABASE_DRIVER=pdo_sqlite
#        - SULU_DATABASE_PATH=test.sqlite

before_script:
  - if [ ! -d downloads ]; then mkdir downloads; fi
  - |
    if [[ $SULU_PHPCR_TRANSPORT = jackrabbit ]]; then
        if [ ! -f downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar ]; then
            cd downloads
            wget http://archive.apache.org/dist/jackrabbit/$JACKRABBIT_VERSION/jackrabbit-standalone-$JACKRABBIT_VERSION.jar
            cd -
        fi
        java -jar downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar > /dev/null &
    fi
  # the content tests are intensive and there are memory leaks, this is more pronounced with the Jackalope DBAL PHPCR implementation.
  - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ $SULU_PHPCR_TRANSPORT = jackrabbit ]]; then composer require jackalope/jackalope-jackrabbit:~1.2 --no-update --no-interaction ; fi
  - composer update $COMPOSER_FLAGS

script:
  - time ./bin/runtests -i -a $TEST_FLAGS

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
