sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - downloads

env:
  global:
    - APP_ENV="test"
    - APP_SECRET=a448d1dfcaa563fce56c2fd9981f662b
    - MAILER_URL=null://localhost
    - SULU_ADMIN_EMAIL=
    - JACKRABBIT_VERSION=2.12.0
    - PHPCR_TRANSPORT=doctrinedbal
    - TEST_FLAGS=""
    - DATABASE_URL=mysql://root:@127.0.0.1/sulu_test
    - DATABASE_CHARSET=utf8mb4
    - DATABASE_COLLATE=utf8mb4_unicode_ci

matrix:
  include:
    - language: php
      php: 7.2
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
        - SYMFONY_DEPRECATIONS_HELPER="weak"

    - language: php
      php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
        - DATABASE_URL=postgres://postgres:postgres@127.0.0.1/sulu_test
        - PHPCR_TRANSPORT=jackrabbit
        - DATABASE_CHARSET=UTF8
        - DATABASE_COLLATE=
        # restart jackrabbit after each suite see: https://github.com/sulu-io/sulu/issues/2137
        - TEST_FLAGS="--jackrabbit-restart"
        - SYMFONY_DEPRECATIONS_HELPER="weak"

before_script:
  - if [ ! -d downloads ]; then mkdir downloads; fi
  - |
    if [[ $PHPCR_TRANSPORT = jackrabbit ]]; then
        if [ ! -f downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar ]; then
            cd downloads
            wget http://archive.apache.org/dist/jackrabbit/$JACKRABBIT_VERSION/jackrabbit-standalone-$JACKRABBIT_VERSION.jar
            cd -
        fi
        java -jar downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar > /dev/null &
    fi
  # the content tests are intensive and there are memory leaks, this is more pronounced with the Jackalope DBAL PHPCR implementation.
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ $PHPCR_TRANSPORT = jackrabbit ]]; then composer require jackalope/jackalope-jackrabbit:~1.2 --no-update --no-interaction ; fi
  - composer validate --strict
  - composer update $COMPOSER_FLAGS

script:
  - time ./bin/runtests -i -a $TEST_FLAGS

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
