build: false

platform:
  - x64

environment:
  matrix:
    # see http://windows.php.net/downloads/releases/ for available versions
    - PHP_VERSION: 5.6.33
      SYMFONY__DATABASE__PASSWORD: Password12!
    - PHP_VERSION: 7.1.14
      JACKRABBIT_VERSION: 2.12.0
      SYMFONY__PHPCR__TRANSPORT: jackrabbit
      SYMFONY__DATABASE__PASSWORD: Password12!

services:
  - mysql

hosts:
  localhost: 127.0.0.1

init:
  - SET PATH=C:\tools\php;%PATH%

cache:
  - '%APPDATA%\Composer'
  - '%LOCALAPPDATA%\Composer'
  - jackrabbit-standalone-%JACKRABBIT_VERSION%.jar
  # Redownload when appveyor.yml changed
  - C:\tools\php -> appveyor.yml
  - C:\tools\composer.phar -> appveyor.yml

install:
  # disable wuauserv service
  - ps: Set-Service wuauserv -StartupType Manual

  # install jackrabbit
  - IF NOT EXIST jackrabbit-standalone-%JACKRABBIT_VERSION%.jar (
        IF "%SYMFONY__PHPCR__TRANSPORT%" == "jackrabbit" (
            cd %APPVEYOR_BUILD_FOLDER%
            && appveyor DownloadFile http://archive.apache.org/dist/jackrabbit/%JACKRABBIT_VERSION%/jackrabbit-standalone-%JACKRABBIT_VERSION%.jar
        )
    )

  # install composer
  - IF NOT EXIST C:\tools\composer.phar (
        cd C:\tools
        && appveyor DownloadFile https://getcomposer.org/composer.phar
    )

  # install php
  - IF NOT EXIST C:\tools\php (
        cinst --yes --allow-empty-checksums php --version %PHP_VERSION% --params '/InstallDir:C:\tools\php'
    )

  # configure PHP and enable extensions.
  - cd C:\tools\php
  - ps: cat php.ini-production | %{$_ -replace "memory_limit = 128M","memory_limit = -1"} | Out-File -Encoding "Default" php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini

before_test:
  - cd %APPVEYOR_BUILD_FOLDER%

  # Start Jackrabbit
  - java -version
  - ps: if ($env:SYMFONY__PHPCR__TRANSPORT -MATCH "jackrabbit") { $argumentList='-jar jackrabbit-standalone-' + $env:JACKRABBIT_VERSION + '.jar'; Start-Process -FilePath java -ArgumentList $argumentList }

  # Composer install
  - php -dmemory_limit=-1 C:\tools\composer.phar update --no-interaction --no-progress --prefer-dist --no-ansi
  - IF "%SYMFONY__PHPCR__TRANSPORT%" == "jackrabbit" (
        php -dmemory_limit=-1 C:\tools\composer.phar require jackalope/jackalope-jackrabbit:~1.2
    )

test_script:
   - cd %APPVEYOR_BUILD_FOLDER%
   - php bin/runtests -i -a
