version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    command: '--max_connections=1000'
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
