sulu_admin:
    path:  /
    defaults:
        _controller: SuluAdminBundle:Admin:index

sulu_admin.navigation:
    type: rest
    resource: Sulu\Bundle\AdminBundle\Controller\NavigationsController

sulu_admin.routes:
    path: /bundles
    defaults:
        _controller: SuluAdminBundle:Admin:bundles

sulu_admin.contexts:
    path: /contexts
    defaults:
        _controller: SuluAdminBundle:Admin:contexts

sulu_admin.login:
    path: /login
    defaults: { _controller: SuluAdminBundle:Security:login }

sulu_admin.login_check:
    path: /login_check

logout:
    path: /logout

sulu_admin.widgets.contactInfo:
    pattern: /widget-groups/contact-info
    defaults: { _controller: SuluAdminBundle:WidgetGroups:contactInfo }

sulu_admin.widgets.accountInfo:
    pattern: /widget-groups/account-info
    defaults: { _controller: SuluAdminBundle:WidgetGroups:accountInfo }

sulu_admin.widgets.contactDetail:
    pattern: /widget-groups/contact-detail
    defaults: { _controller: SuluAdminBundle:WidgetGroups:contactDetail }

sulu_admin.widgets.accountDetail:
    pattern: /widget-groups/account-detail
    defaults: { _controller: SuluAdminBundle:WidgetGroups:accountDetail }
