imports:
    - { resource: sulu.yml }

sulu_admin:
    name: SULU 2.0
    email: installation.email@sulu.test

sulu_security:
    checker:
        enabled: true

sulu_document_manager:
    default_session: default
    live_session: live

sulu_test:
    enable_test_user_provider: true
