framework:
    session:
        storage_id: session.storage.mock_file
        handler_id: ~

    lock: 'flock://%kernel.project_dir%/var/lock'

security:
    access_decision_manager:
        strategy: affirmative

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User: plaintext

    providers:
        testprovider:
            id: test_user_provider

    firewalls:
        test:
            http_basic:
