framework:
    secret: secret
    router: { resource: '%kernel.project_dir%/config/routing.yml' }
    test: ~
    profiler:
        enabled: false
    mailer:
        dsn: 'null://null'

    lock: 'flock://%kernel.project_dir%/var/lock'

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
    dbal:
        url: '%database.url%'
        charset: '%database.charset%'
        default_table_options:
            charset: '%database.charset%'
            collate: '%database.collate%'

sulu_document_manager:
    sessions:
        default:
            backend:
                type: '%phpcr.transport%'
                url:  '%phpcr.backend_url%'
            workspace: '%phpcr.workspace%'
            username: '%phpcr.username%'
            password: '%phpcr.password%'
        live:
            backend:
                type: '%phpcr.transport%'
                url:  '%phpcr.backend_url%'
            workspace: '%phpcr.workspace%_live'
            username: '%phpcr.username%'
            password: '%phpcr.password%'
    debug: false

jms_serializer:
    metadata:
        debug: '%kernel.debug%'

sulu_website:
    twig:
        attributes:
            urls: false
            path: false
