sulu_security.roles:
    type: rest
    name_prefix: sulu_security.
    resource: sulu_security.role_controller

sulu_security.role_settings:
    type: rest
    name_prefix: sulu_security.
    parent: sulu_security.roles
    resource: sulu_security.role_setting_controller

sulu_security.users:
    type: rest
    name_prefix: sulu_security.
    resource: sulu_security.user_controller

sulu_security.post_user_trigger:
    path: /users/{id}
    methods: POST
    defaults:
        _controller: sulu_security.user_controller::postTriggerAction

sulu_security.permissions:
    type: rest
    name_prefix: sulu_security.
    resource: sulu_security.permission_controller

sulu_security.contexts:
    type: rest
    name_prefix: sulu_security.
    resource: sulu_security.contexts_controller

sulu_security.profile:
    type: rest
    name_prefix: sulu_security.
    resource: sulu_security.profile_controller
