parameters:
    sulu.test_user_provider.class: Sulu\Bundle\TestBundle\Testing\TestUserProvider
    sulu.test_voter.class: Sulu\Bundle\TestBundle\Testing\TestVoter
    sulu_test.test_user_repository.class: Sulu\Bundle\TestBundle\Entity\TestUserRepository

services:
    test_user_provider:
        class: "%sulu.test_user_provider.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    test_voter:
        class: "%sulu.test_voter.class%"
        public: false
        tags:
            - { name: security.voter }

    sulu_security.user_repository:
        class: %sulu_test.test_user_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["SuluTestBundle:TestUser"]
