sulu_resource.filter:
    type: rest
    resource: Sulu\Bundle\ResourceBundle\Controller\FilterController

sulu_resource.operator:
    type: rest
    resource: Sulu\Bundle\ResourceBundle\Controller\OperatorController
