imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: 'd884940103091c3ce4e952dfa68ef24278d9986c'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: '%database.driver%'
        host: '%database.host%'
        port: '%database.port%'
        dbname: '%database.name%'
        user: '%database.user%'
        password: '%database.password%'
        path: '%database.path%'
        server_version: '%database.version%'
        charset: '%database.charset%'
        default_table_options:
            charset: '%database.charset%'
            collate: '%database.collate%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: 'smtp'
    host: '127.0.0.1'
    username: ~
    password: ~
    spool: { type: memory }

# DoctrineCache Configuration
doctrine_cache:
    providers:
        phpcr_meta:
            type: 'file_system'
        phpcr_nodes:
            type: 'file_system'

# MassiveSearch Configuration
massive_search:
    adapters:
        zend_lucene:
            basepath: '%kernel.var_dir%/indexes'

# JMS Serializer Configuration
jms_serializer:
    metadata:
        debug: '%kernel.debug%'

# SuluCore Configuration
sulu_core:
    webspace:
        config_dir: '%kernel.root_dir%/Resources/webspaces'
    content:
        structure:
            default_type:
                snippet: 'default'
            paths:
                homepage:
                    path: '%kernel.root_dir%/Resources/templates/pages'
                    type: 'home'
                page:
                    path: '%kernel.root_dir%/Resources/templates/pages'
                    type: 'page'
                snippet:
                    path: '%kernel.root_dir%/Resources/templates/snippets'
                    type: 'snippet'

# SuluAdmin Configuration
sulu_admin:
    name: 'Sulu'
    email: 'hello@sulu.io'

# SuluDocumentManager Configuration
sulu_document_manager:
    sessions:
        default:
            backend:
                type: '%phpcr.transport%'
                url:  '%phpcr.backend_url%'
            workspace: '%phpcr.workspace%'
            username: '%phpcr.username%'
            password: '%phpcr.password%'
        live:
            backend:
                type: '%phpcr.transport%'
                url:  '%phpcr.backend_url%'
            workspace: '%phpcr.workspace%_live'
            username: '%phpcr.username%'
            password: '%phpcr.password%'

# SuluWebsocket Configuration
sulu_websocket:
    server:
        http_host: 'sulu.io'
        port: '9876'

# SuluWebsite Configuration
sulu_website:
    sitemap:
        dump_dir: '%kernel.var_dir%/sitemaps'

# SuluHttpCache Configuration
sulu_http_cache:
    handlers:
        debug:
            enabled: '%kernel.debug%'

# SuluMedia Configuration
sulu_media:
    storage:
        local:
            path: '%kernel.var_dir%/uploads/media'

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
services:
    jms_serializer.cache_naming_strategy: '@sulu_core.serialize_caching_strategy'
