version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      # Node
      - run: npm install
      - run: npm run lint:js
      - run: npm run lint:scss
      - run: npm run flow
      - run: npm run styleguide:build
      - run: npm test -- --maxWorkers=4
