version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.3-node
    steps:
      - checkout
      - run:
            name: Check error for yarn install
            command: tests/js/check-yarn-warning.sh
      - run: npm install
      - run: npm run lint:js
      - run: npm run lint:scss
      - run: npm run flow -- check
      - run: npm run depcruise
      - run: npm run styleguide:build
      - run: npm test -- --maxWorkers=4
      - run: rm composer.json && composer require friendsofsymfony/jsrouting-bundle:^2.3 --no-interaction
      - run: npm run build
