sulu_content.rl:
    type: rest
    resource: Sulu\Bundle\ContentBundle\Controller\NodeResourcelocatorController

sulu_content.node:
    type: rest
    resource: Sulu\Bundle\ContentBundle\Controller\NodeController

sulu_content.node.seo:
    type: rest
    parent: sulu_content.node
    resource: Sulu\Bundle\ContentBundle\Controller\SeoController

sulu_content.webspace.localization:
    type: rest
    resource: Sulu\Bundle\ContentBundle\Controller\WebspaceLocalizationController
