sulu_preview.preview_link:
    type: rest
    name_prefix: sulu_preview.
    resource: sulu_preview.preview_link_controller

sulu_preview.post_preview_link_trigger:
    path: /preview-links/{resourceId}.{_format}
    methods: POST
    defaults:
        _controller: sulu_preview.preview_link_controller::postTriggerAction
        _format: json
