sulu_preview.public_preview:
    path: "/{token}"
    defaults:
        _controller: sulu_preview.public_preview_controller::previewAction

sulu_preview.public_render:
    path: "/{token}/render"
    defaults:
        _controller: sulu_preview.public_preview_controller::renderAction
