sulu_category.categories:
    type: rest
    name_prefix: sulu_category.
    resource: Sulu\Bundle\CategoryBundle\Controller\CategoryController

sulu_category.post_category_trigger:
    path: /categories/{id}.{_format}
    methods: POST
    defaults:
        _controller: Sulu\Bundle\CategoryBundle\Controller\CategoryController::postTriggerAction
        _format: json

sulu_category.keywords:
    type: rest
    name_prefix: sulu_category.
    parent: sulu_category.categories
    resource: Sulu\Bundle\CategoryBundle\Controller\KeywordController
