sulu_reference.references:
    path: /admin/api/references.{_format}
    methods: GET
    controller: sulu_reference.reference_controller:cgetAction
    format: json|csv
    defaults:
        _format: json
