sulu_tag.tags:
    type: rest
    name_prefix: sulu_tag.
    resource: sulu_tag.tag_controller

sulu_tag.post_tag_merge:
    path: /tags/merge.{_format}
    methods: POST
    defaults:
        _controller: sulu_tag.tag_controller::postMergeAction
        _format: json
