parameters:
    sulu_tag.admin.class: Sulu\Bundle\TagBundle\Admin\SuluTagAdmin
    sulu_tag.tag_manager.class: Sulu\Bundle\TagBundle\Tag\TagManager
    sulu_tag.tag_repository.class: Sulu\Bundle\TagBundle\Entity\TagRepository
    sulu_tag.content.type.tag_list.class: Sulu\Bundle\TagBundle\Content\Types\TagList

services:
    sulu_tag.admin:
        class: %sulu_tag.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
            - { name: sulu.admin }
            - { name: sulu.context, context: admin }

    sulu_tag.tag_repository:
        class: %sulu_tag.tag_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["SuluTagBundle:Tag"]

    sulu_tag.tag_manager:
        class: %sulu_tag.tag_manager.class%
        arguments:
            - "@sulu_tag.tag_repository"
            - "@sulu_security.user_repository"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    # Content types
    sulu_tag.content.type.tag_list:
        class: %sulu_tag.content.type.tag_list.class%
        arguments: ["@sulu_tag.tag_manager", %sulu_tag.content.type.tag_list.template%]
        tags:
            - { name: sulu.content.type, alias: tag_list }
