sulu_contact.contacts:
    type: rest
    name_prefix: sulu_contact.
    resource: Sulu\Bundle\ContactBundle\Controller\ContactController

sulu_contact.accounts:
    type: rest
    name_prefix: sulu_contact.
    resource: Sulu\Bundle\ContactBundle\Controller\AccountController

sulu_contact.contacttitle:
    type: rest
    name_prefix: sulu_contact.
    resource: Sulu\Bundle\ContactBundle\Controller\ContactTitleController

sulu_contact.contactposition:
    type: rest
    name_prefix: sulu_contact.
    resource: Sulu\Bundle\ContactBundle\Controller\PositionController

sulu_contact.account_medias:
    type: rest
    name_prefix: sulu_contact.
    parent: sulu_contact.accounts
    resource: Sulu\Bundle\ContactBundle\Controller\AccountMediaController

sulu_contact.contact_medias:
    type: rest
    name_prefix: sulu_contact.
    parent: sulu_contact.contacts
    resource: Sulu\Bundle\ContactBundle\Controller\ContactMediaController
