contact_form:
    path: /template/contact/form.html
    defaults: { _controller: SuluContactBundle:Template:contactForm }

account_form:
    path: /template/account/form.html
    defaults: { _controller: SuluContactBundle:Template:accountForm }

account_form_contact_list:
    path: /template/account/form/contact.html
    defaults: { _controller: SuluContactBundle:Template:accountFormContactList }

contact_list:
    path: /template/contact/list.html
    defaults: { _controller: SuluContactBundle:Template:contactList }

account_list:
    path: /template/account/list.html
    defaults: { _controller: SuluContactBundle:Template:accountList }

basic_documents:
    path: /template/basic/documents.html
    defaults: { _controller: SuluContactBundle:Template:basicDocuments }
