contact_form:
    pattern: /template/contact/form.html
    defaults: { _controller: SuluContactBundle:Template:contactForm }

account_form:
    pattern: /template/account/form.html
    defaults: { _controller: SuluContactBundle:Template:accountForm }

contact_list:
    pattern: /template/contact/list.html
    defaults: { _controller: SuluContactBundle:Template:contactList }

account_list:
    pattern: /template/account/list.html
    defaults: { _controller: SuluContactBundle:Template:accountList }

basic_documents:
    pattern: /template/basic/documents.html
    defaults: { _controller: SuluContactBundle:Template:basicDocuments }
