sulu_media.template.collection.settings:
    path: /template/collection/settings.html
    defaults: { _controller: SuluMediaBundle:Template:collectionSettings }

sulu_media.template.collection.new:
    path: /template/collection/new.html
    defaults: { _controller: SuluMediaBundle:Template:collectionNew }

sulu_media.template.media.multiple_edit:
    path: /template/media/multiple-edit.html
    defaults: { _controller: SuluMediaBundle:Template:multipleEdit }

sulu_media.redirect:
    path: /redirect/media/{id}
    defaults: { _controller: SuluMediaBundle:MediaRedirect:redirect }
