sulu_media.website.image.proxy:
    path: %sulu_media.format_cache.media_proxy_path%
    defaults: { _controller: SuluMediaBundle:MediaStream:getImage }
    requirements:
        slug: .*

sulu_media.website.media.download:
    path: %sulu_media.media_manager.media_download_path%
    defaults: { _controller: SuluMediaBundle:MediaStream:download }
    requirements:
        slug: .*
